version: '3'
services:
  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      POSTGRES_DB: sparser
      POSTGRES_USER: sparseruser
      POSTGRES_PASSWORD: superunsequrepasswordneedchange
      POSTGRES_URI : {{cookiecutter.postgres_uri}}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  app:
    container_name: {{cookiecutter.app_name}}
    build: .
    ports: 
      - 8080:8800 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    {% if cookiecutter.postgres_uri !="n" -%}
    # Add different Db confs here If it is postgress or mongo or redis
    {%endif -%}
    depends_on:
      - fullstack-postgres          

    networks:
      - fullstack
    
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   depends_on:
  #     - fullstack-postgres
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - fullstack
  #   restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: local # bridge
