version: '3'
services:
  app:
    container_name: {{cookiecutter.app_name}}
    build: .
    ports: 
      - 8080:8800 
    restart: on-failure
    # volumes:
    #   - api:/usr/src/app/
    # depends_on:
    #   # - fullstack-postgres          # Uncomment this when using postgres.
    #   - fullstack-mysql           # Uncomment this when using mysql.
    # networks:
    #   - backend